{% set name = "friendly-styles" %}
{% set version = "0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/friendly_styles-{{ version }}.tar.gz
  sha256: 96d935971fd7b6d782d6fb1346d57be2b075bce086997956bdff85cb4d0ad6cd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pygments >=2
    - python >={{ python_min }}

test:
  imports:
    - friendly_styles
  commands:
    - pip check
    - "'SELECT * FROM table LIMIT 10' | pygmentize -s -l SQL -O style=friendly_light"  # [unix]
    - "'SELECT * FROM table LIMIT 10' | pygmentize -s -l SQL -O style=friendly_dark"  # [unix]

  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/friendly-traceback/friendly_styles
  summary: Pygments styles designed for friendly/friendly-traceback
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
